language: node_js
node_js: "8.11.1"

notifications:
  email: false

env:
  global:
    - CC_TEST_REPORTER_ID=664001952d6b2b65d1b7ef159f1352a69b3bac46ad3b3ccd159c2390e29c9256

before_script:
  - npm install nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nyc --reporter=lcov --reporter=text-lcov npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: true

after_success: 'npm run coverage'
after_fail: 'npm run coverage'
